// NOTE: don't use key since its reserved usually when mapping over objects

export const TrainerCertifications: Array<{ label: string; value: string }> = [
  { label: "Certificate III in Fitness", value: "CertIII" },
  { label: "Certificate IV in Fitness", value: "CertIV" },
  { label: "Diploma of Fitness", value: "DiplomaofFitness" },
  { label: "ASCA (Strength and Conditioning)", value: "ASCA" },
  { label: "ASCA Level 1 Certification", value: "ASCALevel1Cert" },
  { label: "ASCA Level 2 Certification", value: "ASCALevel2Cert" },
  { label: "ASCA Level 3 Certification", value: "ASCALevel3Cert" },
  { label: "Nutrition Certifications", value: "NutritionCert" },
  { label: "Level 1 Sports Nutrition Certification", value: "Level1SportsNutritionCert" },
  { label: "Level 2 Sports Nutrition Certification", value: "Level2SportsNutritionCert" },
  { label: "Nutrition for Personal Trainers Certification", value: "NutritionforPTCert" },
  { label: "Yoga Teacher Training", value: "YogaTeacherTraining" },
  { label: "Yoga Teacher Training (200 Hours)", value: "YogaTeacherTraining200Hours" },
  { label: "Yoga Teacher Training (500 Hours)", value: "YogaTeacherTraining500Hours" },
  { label: "Specialty Certifications", value: "SpecialtyCertifications" },
  { label: "Pilates Instructor Certification", value: "PilatesInstructorCertification" },
  { label: "Group Fitness Instructor Certification", value: "GroupFitnessInstructorCertification" },
  { label: "Les Mills Instructor Certifications", value: "LesMillsInstructorCertifications" },
  { label: "Aqua Aerobics Instructor Certification", value: "AquaAerobicsInstructorCertification" },
  { label: "Boxing for Fitness Certification", value: "BoxingforFitnessCertification" },
  { label: "CrossFit Level 1 Certification", value: "CrossFitLevel1Certification" },
  { label: "TRX Suspension Training Certification", value: "TRXSuspensionTrainingCertification" },
  { label: "Kettlebell Instructor Certification", value: "KettlebellInstructorCertification" },
  { label: "Older Adults Fitness Certification", value: "OlderAdultsFitnessCertification" },
  { label: "Pre/Postnatal Exercise Certification", value: "PrePostnatalExerciseCertification" },
  { label: "Children's Fitness Certification", value: "ChildrensFitnessCertification" },
  { label: "Higher Education Degrees", value: "HigherEducationDegrees" },
  { label: "Bachelor of Exercise and Sport Science", value: "BachelorofExerciseandSportScience" },
  { label: "Bachelor of Health and Physical Education", value: "BachelorofHealthandPhysicalEducation" },
  { label: "Bachelor of Applied Fitness", value: "BachelorofAppliedFitness" },
  { label: "Bachelor of Sport and Exercise Science (Strength and Conditioning)", value: "BachelorofSportandExerciseScience" },
  { label: "Bachelor of Exercise Physiology", value: "BachelorofExercisePhysiology" },
  { label: "Graduate Diploma of Exercise Science", value: "GraduateDiplomaofExerciseScience" },
  { label: "Master of Clinical Exercise Physiology", value: "MasterofClinicalExercisePhysiology" },
  { label: "Master of Sports Coaching", value: "MasterofSportsCoaching" },
  { label: "PhD in Exercise Science/Sport Science", value: "PhDinExerciseScienceSportScience" },
];

export const TrainerSpecialties: Array<{ label: string; value: string }> = [
  { label: "Weight Loss", value: "WEIGHTLOSS" },
  { label: "Muscle Building (Hypertrophy)", value: "MUSCLEBUILDING" },
  { label: "Strength Training", value: "STRENGTHTRAINING" },
  { label: "Cardiovascular Fitness", value: "CARDIOVASCULAR" },
  { label: "Endurance Training", value: "ENDURANCE" },
  { label: "Mobility and Flexibility", value: "MOBILITY" },
  { label: "Posture Correction", value: "POSTURECORRECTION" },
  { label: "Rehabilitation and Injury Prevention", value: "REHABILITATION" },
  { label: "Functional Training", value: "FUNCTIONALTRAINING" },
  { label: "Pre/Postnatal Fitness", value: "PREPOSTNATAL" },
  { label: "Sports-Specific Training", value: "SPORTSTRAINING" },
  { label: "High-Intensity Interval Training (HIIT)", value: "HIIT" },
  { label: "Bodyweight Training (Calisthenics)", value: "CALISTHENICS" },
  { label: "Powerlifting", value: "POWERLIFTING" },
  { label: "Olympic Lifting", value: "OLYMPICLIFTING" },
  { label: "CrossFit", value: "CROSSFIT" },
  { label: "Gymnastics Conditioning", value: "GYMNASTICS" },
  { label: "Martial Arts Fitness", value: "MARTIALART" },
  { label: "Senior Fitness", value: "SENIORFITNESS" },
  { label: "Youth Training", value: "YOUTHTRAINING" },
  { label: "Speed and Agility", value: "SPEEDAGILITY" },
  { label: "Nutritional Coaching", value: "NUTRITIONALCOACHING" },
  { label: "Mental and Emotional Well-being", value: "MENTALWELLBEING" },
  { label: "Bodybuilding and Competition Prep", value: "BODYBUILDINGCOMPETITION" },
  { label: "Holistic Health and Wellness", value: "HOLISTICHEALTH" },
  { label: "Online Coaching", value: "ONLINECOACH" },
  { label: "Outdoor Training", value: "TRAINOUTDOOR" },
  { label: "Yoga", value: "YOGA" },
  { label: "Pilates", value: "PILATES" },
  { label: "Group Fitness", value: "GROUPFITNESS" },
  { label: "TRX/Suspension Training", value: "TRXSUSPENSION" },
  { label: "Kettlebell Training", value: "KETTLEBELL" },
  { label: "Plyometric Training", value: "PLYOMETRICTRAINING" },
  { label: "Circuit Training", value: "CIRCUITTRAINING" },
  { label: "Balance and Stability Training", value: "BALANCESTABILITY" },
  { label: "Core Strength", value: "BUILDCORE" },
];
